import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  ALL_CASE_IDS,
  CASE_FIXTURES,
  FIXTURES,
  REQUIRED_ACCOUNT_ROLES,
  fixturesForCases,
  type FixtureKey,
} from '../fixtures/caseData';
import {
  cleanupSeedData,
  createSeedContext,
  verifySecurityProbeRows,
  type SeedContext,
} from '../fixtures/factories';
import { usersWithCreds } from '../fixtures/users';

/**
 * Seed project (`playwright test --project=seed`, or `npm run test:e2e:seed`).
 *
 * Provisions exactly the fixtures required by the requested case IDs.
 * Env flags:
 *   E2E_SEED_CASES   comma-separated case IDs, or "all" (default)
 *   E2E_SEED_CLEANUP delete all `[UAT]` rows first
 *   E2E_SEED_VERIFY  fail the run if a required fixture is still missing
 *   E2E_SEED_DOCS    (re)generate docs/e2e-test-data.md
 */

const dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(dirname, '../..');

function requestedCases(): string[] {
  const raw = (process.env.E2E_SEED_CASES || 'all').trim();
  if (!raw || raw.toLowerCase() === 'all') return ALL_CASE_IDS;
  return raw
    .split(',')
    .map((c) => c.trim().toUpperCase())
    .filter(Boolean);
}

test.describe.configure({ mode: 'serial' });

test('seed per-case test data', async () => {
  test.setTimeout(10 * 60_000);
  const cases = requestedCases();
  const unknown = cases.filter((c) => !CASE_FIXTURES[c]);
  expect(unknown, `Unknown case IDs: ${unknown.join(', ')}`).toEqual([]);

  const fixtures = fixturesForCases(cases);
  console.log(`Seeding ${fixtures.length} fixture(s) for ${cases.length} case(s).`);

  if (process.env.E2E_SEED_DOCS) writeTestDataDoc();

  let ctx: SeedContext;
  try {
    ctx = await createSeedContext();
  } catch (err) {
    test.skip(true, (err as Error).message);
    return;
  }

  if (process.env.E2E_SEED_CLEANUP) {
    console.log('Cleaning existing [UAT] rows…');
    await cleanupSeedData(ctx);
  }

  // Accounts are never created by the seeder — they are verified.
  if (fixtures.includes('accounts')) {
    const configured = usersWithCreds().map((u) => u.role);
    const missing = REQUIRED_ACCOUNT_ROLES.filter((r) => !configured.includes(r));
    if (missing.length) {
      ctx.warnings.push(`accounts: no credentials configured for ${missing.join(', ')}`);
      console.log(`  ! accounts fixture partial — missing creds for ${missing.join(', ')}`);
    } else {
      console.log('  ✓ accounts — credentials present for every role');
    }
  }

  for (const key of fixtures) {
    if (key === 'accounts') continue;
    const def = FIXTURES[key];
    console.log(`  → ${key}: ${def.description}`);
    await def.provision(ctx);
  }

  const emptyProbeTables = fixtures.includes('security.probeRows')
    ? await verifySecurityProbeRows(ctx)
    : [];

  console.log('\nCreated:', JSON.stringify(ctx.created));
  console.log('Reused: ', JSON.stringify(ctx.reused));
  if (ctx.warnings.length) console.log('Warnings:\n - ' + ctx.warnings.join('\n - '));

  if (process.env.E2E_SEED_VERIFY) {
    expect(emptyProbeTables, `Security probe tables still empty: ${emptyProbeTables.join(', ')}`).toEqual([]);
    expect(ctx.warnings, `Seeding warnings:\n${ctx.warnings.join('\n')}`).toEqual([]);
  }
});

function writeTestDataDoc() {
  const lines: string[] = [
    '# E2E per-case test data',
    '',
    'Generated by `npm run test:e2e:seed:docs` — do not edit by hand.',
    'Source of truth: `e2e/fixtures/caseData.ts` and `e2e/fixtures/factories.ts`.',
    '',
    '## Fixtures',
    '',
    '| Fixture | Section 8 area | Provides | Depends on |',
    '| --- | --- | --- | --- |',
  ];
  for (const def of Object.values(FIXTURES)) {
    lines.push(
      `| \`${def.key}\` | ${def.section8} | ${def.description} | ${
        (def.requires || []).map((r) => `\`${r}\``).join(', ') || '—'
      } |`,
    );
  }
  lines.push('', '## Case → fixtures', '', '| Case | Fixtures provisioned (resolved order) |', '| --- | --- |');
  for (const id of ALL_CASE_IDS) {
    const resolved = fixturesForCases([id]) as FixtureKey[];
    lines.push(`| ${id} | ${resolved.map((f) => `\`${f}\``).join(', ')} |`);
  }
  lines.push(
    '',
    '## Usage',
    '',
    '```bash',
    '# everything (default)',
    'npm run test:e2e:seed',
    '',
    '# only what a single case needs',
    'node scripts/seed-e2e-data.mjs --case UAT-KRI-03',
    '',
    '# reset the [UAT] dataset, reseed and assert completeness',
    'node scripts/seed-e2e-data.mjs --all --cleanup --verify',
    '```',
    '',
    'All seeded rows are prefixed `[UAT]` and are removed by `--cleanup`.',
    '',
  );
  const out = path.join(ROOT, 'docs/e2e-test-data.md');
  fs.writeFileSync(out, lines.join('\n'));
  console.log(`Wrote ${path.relative(ROOT, out)}`);
}
