#!/usr/bin/env bun
/**
 * Role-permutation coverage report generator.
 *
 * For every role in `src/lib/permissions.ts` it emits:
 *   - the routes the smoke suite visits (expected reachable vs. blocked)
 *   - the sidebar links it asserts present/absent
 *   - the gated CTAs it probes (expected visible/hidden)
 * Each row links to the exact `expect` line in e2e/tests/role-smoke.spec.ts
 * that makes the assertion, so every expectation is traceable to code.
 *
 * Usage: bun scripts/role-coverage.ts   (npm run test:e2e:role-report)
 */
import fs from 'node:fs';
import path from 'node:path';
import {
  ALL_ROLES,
  ROUTE_ACCESS,
  ACTION_ACCESS,
  canSeeInSidebar,
  canAccessRoute,
  canPerformAction,
  type UserRole,
} from '../src/lib/permissions';

const root = path.resolve(import.meta.dir, '..');
const SPEC_REL = 'e2e/tests/role-smoke.spec.ts';
const SPEC = path.join(root, SPEC_REL);
const OUT = path.join(root, 'docs/role-permutation-coverage.md');

const LANDING: Record<UserRole, string> = {
  ADMIN: '/app',
  RMD: '/app',
  CRO: '/app',
  RC: '/risk-register',
  RR: '/risk-register',
  RO: '/risk-register',
  EC: '/executive-summary',
  ERMSC: '/executive-summary',
  RCB: '/executive-summary',
  SUPERVISOR: '/whistleblow/cases',
  USER: '/app',
};

// --- locate the assertion lines in the spec -------------------------------
const specLines = fs.readFileSync(SPEC, 'utf8').split('\n');
function findLine(needle: string): number {
  const i = specLines.findIndex((l) => l.includes(needle));
  if (i === -1) throw new Error(`Assertion anchor not found in ${SPEC_REL}: ${needle}`);
  return i + 1;
}
const LINES = {
  landing: findLine('should land on'),
  route: findLine('must NOT reach'),
  sidebar: findLine('sidebar should'),
  cta: findLine('CTA on'),
  coverage: findLine('each configured role must appear once'),
};
const ref = (line: number) => `[${SPEC_REL}:${line}](../${SPEC_REL}#L${line})`;

// --- probes mirrored from the spec ----------------------------------------
const CTA_PROBES = [
  { action: 'risk.create', path: '/risk-register', name: 'add (new )?risk|new risk|risk wizard' },
  { action: 'bcp.create', path: '/business-continuity', name: 'add (new )?(bcp|plan)|new plan' },
  { action: 'kri.manage', path: '/kris', name: 'new indicator' },
  { action: 'incident.create', path: '/incidents', name: 'report incident|add incident|new incident' },
  { action: 'boardreport.generate', path: '/board-reports', name: '^generate$|generate reports?' },
  { action: 'user.manage', path: '/user-management', name: 'invite user|add user|new user' },
];

const SIDEBAR_ROUTES = ROUTE_ACCESS.filter((r) => !r.hiddenFromSidebar && !r.path.includes(':')).map(
  (r) => r.path,
);
const label = (id: string) => ACTION_ACCESS.find((a) => a.id === id)?.label ?? id;
const server = (id: string) => ACTION_ACCESS.find((a) => a.id === id)?.serverCounterpart ?? '—';

// --- report ----------------------------------------------------------------
const out: string[] = [];
const yn = (b: boolean) => (b ? 'yes' : 'no');

out.push('# Role-permutation coverage report');
out.push('');
out.push(`Generated by \`bun scripts/role-coverage.ts\` from \`src/lib/permissions.ts\` and \`${SPEC_REL}\`. Do not edit by hand.`);
out.push('');
out.push(
  `Roles: **${ALL_ROLES.length}** · routes probed per role: **${SIDEBAR_ROUTES.length}** · CTA probes per role: **${CTA_PROBES.length}** · total assertions: **${
    ALL_ROLES.length * (1 + SIDEBAR_ROUTES.length * 2 + CTA_PROBES.length) + 1
  }**`,
);
out.push('');
out.push('Every expectation below is derived at runtime from the permission matrix; the spec re-computes the same value, so a permission change updates test and report together.');
out.push('');

// summary
out.push('## Summary');
out.push('');
out.push('| Role | Landing | Routes reachable | Routes blocked | Sidebar links | CTAs allowed | CTAs hidden |');
out.push('| --- | --- | --- | --- | --- | --- | --- |');
for (const role of ALL_ROLES) {
  const reach = SIDEBAR_ROUTES.filter((p) => canAccessRoute(role, p));
  const side = SIDEBAR_ROUTES.filter((p) => canSeeInSidebar(role, p));
  const ctaOn = CTA_PROBES.filter((c) => canPerformAction(role, c.action));
  out.push(
    `| ${role} | \`${LANDING[role]}\` | ${reach.length} | ${SIDEBAR_ROUTES.length - reach.length} | ${side.length} | ${ctaOn.length} | ${CTA_PROBES.length - ctaOn.length} |`,
  );
}
out.push('');
out.push('## Suite-level checks');
out.push('');
out.push('| Check | Assertion |');
out.push('| --- | --- |');
out.push(`| Landing page after sign-in (per role) | ${ref(LINES.landing)} |`);
out.push(`| Each configured role appears exactly once | ${ref(LINES.coverage)} |`);
out.push('');

// per role detail
for (const role of ALL_ROLES) {
  out.push(`## ${role}`);
  out.push('');
  out.push(`Landing page: \`${LANDING[role]}\` — asserted at ${ref(LINES.landing)}.`);
  out.push('');
  out.push('### Routes');
  out.push('');
  out.push('| Route | Expected | Sidebar entry expected | Route assertion | Sidebar assertion |');
  out.push('| --- | --- | --- | --- | --- |');
  for (const p of SIDEBAR_ROUTES) {
    // The spec expects reachability to equal sidebar visibility (allowedPaths = visibleRoutesFor).
    const sidebar = canSeeInSidebar(role, p);
    const guard = canAccessRoute(role, p);
    // The smoke suite derives allowedPaths from visibleRoutesFor(), so a
    // guard-only route (deep-link reachable, no sidebar entry) is asserted blocked.
    const expected = sidebar
      ? 'reachable'
      : guard
        ? 'blocked in smoke (guard admits by deep link — covered by journey specs)'
        : 'blocked';
    out.push(
      `| \`${p}\` | ${expected} | ${yn(sidebar)} | ${ref(LINES.route)} | ${ref(LINES.sidebar)} |`,
    );
  }
  out.push('');
  out.push('### Gated CTAs');
  out.push('');
  out.push('| Action | CTA | Page | Expected | Assertion | Server counterpart |');
  out.push('| --- | --- | --- | --- | --- | --- |');
  for (const c of CTA_PROBES) {
    const allowed = canPerformAction(role, c.action);
    const reachablePage = canAccessRoute(role, c.path);
    const expected = !reachablePage
      ? 'skipped (page not reachable)'
      : allowed
        ? 'visible'
        : 'hidden';
    out.push(
      `| \`${c.action}\` | ${label(c.action)} | \`${c.path}\` | ${expected} | ${ref(LINES.cta)} | ${server(c.action)} |`,
    );
  }
  out.push('');
}

out.push('## Notes');
out.push('');
out.push('- Routes flagged *guard admits by deep link* have a legacy `extraGuardRoles` widening: no sidebar entry, so the smoke suite asserts both the hidden link and no navigation from the sidebar; the deep-link path is exercised in the per-journey specs.');
out.push('- CTA rows marked *skipped* are not asserted for that role because the hosting page is blocked — the route assertion already covers the denial.');
out.push('- Parameterised and hidden routes (e.g. `/risk-assessment/:id`, `/profile`) are excluded from the smoke matrix and covered by the per-journey specs in `docs/e2eCoverage.md`.');
out.push('');

fs.writeFileSync(OUT, out.join('\n'));
console.log(`Wrote ${path.relative(root, OUT)} — ${ALL_ROLES.length} roles, ${SIDEBAR_ROUTES.length} routes, ${CTA_PROBES.length} CTA probes.`);
