ALTER TABLE public.business_continuity_plans
  ADD COLUMN IF NOT EXISTS bia_criticality_rating text DEFAULT 'Medium',
  ADD COLUMN IF NOT EXISTS bia_financial_impact numeric,
  ADD COLUMN IF NOT EXISTS bia_operational_impact text,
  ADD COLUMN IF NOT EXISTS bia_reputational_impact text,
  ADD COLUMN IF NOT EXISTS bia_regulatory_impact text,
  ADD COLUMN IF NOT EXISTS bia_max_tolerable_downtime integer,
  ADD COLUMN IF NOT EXISTS bia_peak_periods text[],
  ADD COLUMN IF NOT EXISTS bia_minimum_resources jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS bia_assessment_date date,
  ADD COLUMN IF NOT EXISTS bia_assessed_by uuid,
  ADD COLUMN IF NOT EXISTS test_type text,
  ADD COLUMN IF NOT EXISTS test_scope text,
  ADD COLUMN IF NOT EXISTS test_results text,
  ADD COLUMN IF NOT EXISTS test_findings jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS test_conducted_by uuid;