-- Restore authenticated grants on tables that lost them
GRANT SELECT, INSERT, UPDATE, DELETE ON public.risks TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.business_continuity_plans TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_roles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.approval_history TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.risk_events TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.risk_assessments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.risk_controls TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.risk_audit_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.risk_history TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.bcp_audit_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.control_documents TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.document_acknowledgments TO authenticated;
GRANT SELECT ON public.departments TO authenticated;
GRANT SELECT ON public.strategic_objectives TO authenticated;
GRANT SELECT ON public.risk_categories TO authenticated;
GRANT SELECT ON public.risk_scoring_matrix TO authenticated;
GRANT SELECT ON public.forum_categories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.forum_discussions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.forum_posts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.forum_votes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.forum_moderation_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.training_modules TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.board_report_archives TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.report_schedules TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_predictions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.system_settings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.system_audit_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_activity_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_login_history TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.backup_configurations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.backup_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.backup_restore_operations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.recovery_checklists TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.number_sequences TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.whistleblow_cases TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.whistleblow_messages TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.whistleblow_audit_log TO authenticated;
GRANT SELECT ON public.compliance_risk_register_view TO authenticated;
GRANT SELECT ON public.risk_workflow_audit_view TO authenticated;